medida = float(input('Uma distância em metros: '))
print(f'A medida de {medida}m corresponde a:')
print(f'{medida / 1000}km')
print(f'{medida / 100}hm')
print(f'{medida / 10}dam')
print(f'{medida * 10:.0f}dm')
print(f'{medida * 100:.0f}cm')
print(f'{medida * 100:.0f}mm')
